sysenv: prod
name: fect-be
replicas: 1
  
image:
  repo: 2xnone/appelsin-be
  tag: 0.0.3

ingress:
  host: api.appelsin.dnull.systems
  path: /
  port: 8000

postgresql:
  global:
    postgresql:
      auth:
        postgresPassword: "changeme"
        username: "appelsin"
        password: "appelsin"
        database: "appelsin"
