sysenv: prod
name: fect-be

replicas: 1

image:
  repo: 2xnone/appelsin-be
  tag: 28ebf82

ingress:
  host: api.appelsin.dnull.systems
  path: /
  port: 8000

secrets:
  - secretKey: SECRET_KEY_PROJECT
    remoteRef:
      key: /appelsin/app/be/prod/SECRET_KEY
  - secretKey: POSTGRESQL_PASSWORD
    remoteRef:
      key: /appelsin/app/be/prod/POSTGRESQL_PASSWORD
  - secretKey: POSTGRESQL_ADMIN_PASSWORD
    remoteRef:
      key: /appelsin/infra/postgres/prod

env:
  - name: POSTGRESQL_DATABASE
    value: appelsin
  - name: POSTGRESQL_USERNAME
    value: appelsin
  - name: POSTGRESQL_HOST
    value: fect-be-prod-postgresql.fect-prod.svc
  - name: POSTGRESQL_PORT
    value: "5432"

postgresql:
  global:
    postgresql:
      auth:
        username: appelsin
        database: appelsin
        existingSecret: fect-be
        secretKeys:
          adminPasswordKey: POSTGRESQL_ADMIN_PASSWORD
          userPasswordKey: POSTGRESQL_PASSWORD
