apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: github-
spec:
  entrypoint: main
  volumes:
  - name: docker-config
    secret:
      secretName: docker-config
      items:
      - key: .dockerconfigjson
        path: config.json
  - name: push-key
    secret:
      secretName: deployment-key
      items:
        - key: ssh-privatekey
          path: infra
  arguments:
    parameters:
      - name: repo-owner  # 0
        value: softserve-appelsin
      - name: repo-name   # 1
        value: infra
      - name: repo-url    # 2
        value: https://github.com/softserve-appelsin/infra.git
      - name: repo-ssh    # 3
        value: git@github.com:softserve-appelsin/infra.git
      - name: pr-number   # 4
        value: 4
      - name: sha         # 5
        value: a2319310171f96fe67eb804d3f7f5efc4459ddf8
  templates:
    - name: main
      inputs:
        parameters:
          - name: repo-name
          - name: repo-owner
          - name: repo-url
          - name: repo-ssh
          - name: pr-number
          - name: sha
      dag:
        tasks:
        - name: status-pending
          templateRef:
            name: github-status
            template: main
          arguments:
            parameters:
            - name: name 
              value: argo-events
            - name: description 
              value: testing params
            - name: repo
              value: '{{inputs.parameters.repo-owner}}/{{inputs.parameters.repo-name}}'
            - name: sha
              value: '{{inputs.parameters.sha}}'
            - name: status
              value: pending

        - name: build-image
          depends: status-pending
          templateRef:
            name: kaniko
            template: main
          arguments:
            parameters:
            - name: repo
              value: "{{inputs.parameters.repo-url}}"
            - name: revision
              value: '{{inputs.parameters.sha}}'
            - name: image
              value: 2xnone/appelsin-infra
            - name: dockerfile
              value: dockerfiles/Dockerfile
            - name: context
              value: .

        - name: status-success
          depends: build-image
          templateRef:
            name: github-status
            template: main
          arguments:
            parameters:
            - name: name 
              value: argo-events
            - name: description 
              value: testing params
            - name: repo
              value: '{{inputs.parameters.repo-owner}}/{{inputs.parameters.repo-name}}'
            - name: sha
              value: '{{inputs.parameters.sha}}'
            - name: status
              value: success
