# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/jsonschema/schema.json
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: github-status
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: description
      - name: name
      - name: repo
      - name: sha
      - name: status

  templates:
    - name: main
      inputs:
        parameters:
          - name: description
          - name: name
          - name: repo
          - name: sha
          - name: status
      container:
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"]
        # status: error, failure, pending, or success
        args:
          - >
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/{{`{{inputs.parameters.repo}}`}}/statuses/{{`{{inputs.parameters.sha}}`}} \
              -d '{
                "state": "{{`{{inputs.parameters.status}}`}}",
                "target_url": "https://argo-workflows.dnull.systems/workflows/fect-infra/{{`{{workflow.name}}`}}",
                "description": "{{`{{inputs.parameters.description}}`}}",
                "context": "{{`{{inputs.parameters.name}}`}}"
              }'
        env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-access
                key: token
