---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
spec:
  template:
    serviceAccountName: appelsin-workflow-sa
  dependencies:
    - name: pr-run
      eventSourceName: github
      eventName: all-events
      filters:
        data:
          # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads
          - path: headers.X-Github-Event
            type: string
            value:
              - pull_request
          - path: body.action
            type: string
            value:
              - opened
              - edited
              - reopened
              - synchronize
          - path: body.pull_request.state
            type: string
            value:
              - open
          - path: body.pull_request.base.ref
            type: string
            value:
              - main
  triggers:
    - template:
        name: github-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-
              spec:
                entrypoint: main
                volumes:
                - name: docker-config
                  secret:
                    secretName: docker-config
                    items:
                    - key: .dockerconfigjson
                      path: config.json
                - name: push-key
                  secret:
                    secretName: deployment-key
                    items:
                      - key: ssh-privatekey
                        path: infra
                arguments:
                  parameters:
                    - name: repo-name   # 0
                    - name: repo-owner  # 1
                    - name: repo-url    # 2
                    - name: repo-ssh    # 3
                    - name: sha         # 4
                    - name: pr-number   # 5
                templates:
                  - name: main
                    inputs:
                      parameters:
                        - name: repo-name
                        - name: repo-owner
                        - name: repo-url
                        - name: repo-ssh
                        - name: sha
                        - name: pr-number
                    dag:
                      tasks:
                      - name: status-pending
                        templateRef:
                          name: github-status
                          template: main
                        arguments:
                          parameters:
                          - name: name 
                            value: argo-events
                          - name: description 
                            value: testing params
                          - name: repo
                            value: '{{`{{inputs.parameters.repo-owner}}`}}/{{`{{inputs.parameters.repo-name}}`}}'
                          - name: sha
                            value: '{{`{{inputs.parameters.sha}}`}}'
                          - name: status
                            value: pending

                      - name: build-image
                        depends: status-pending
                        templateRef:
                          name: kaniko
                          template: main
                        arguments:
                          parameters:
                          - name: repo
                            value: "{{`{{inputs.parameters.repo-url}}`}}"
                          - name: revision
                            value: '{{`{{inputs.parameters.sha}}`}}'
                          - name: image
                            value: 2xnone/appelsin-infra
                          - name: dockerfile
                            value: dockerfiles/Dockerfile
                          - name: context
                            value: dockerfiles/

                      - name: status-success
                        depends: build-image
                        templateRef:
                          name: github-status
                          template: main
                        arguments:
                          parameters:
                          - name: name 
                            value: argo-events
                          - name: description 
                            value: testing params
                          - name: repo
                            value: '{{`{{inputs.parameters.repo-owner}}`}}/{{`{{inputs.parameters.repo-name}}`}}'
                          - name: sha
                            value: '{{`{{inputs.parameters.sha}}`}}'
                          - name: status
                            value: success
          parameters:
            # Workflow name  <owner>-<repo>-pr-<pr-no>-<short-sha>
            - src:
                dependencyName: pr-run
                dataTemplate: "{{`{{ .Input.body.repository.owner.login }}`}}-{{`{{ .Input.body.repository.name }}`}}-pr-{{`{{ .Input.body.pull_request.number }}`}}-{{`{{ .Input.body.pull_request.head.sha | substr 0 7 }}`}}"
              dest: metadata.name
              operation: append
            # repo owner
            - src:
                dependencyName: pr-run
                dataKey: body.repository.owner.login
              dest: spec.arguments.parameters.0.value
            # repo name
            - src:
                dependencyName: pr-run
                dataKey: body.repository.name
              dest: spec.arguments.parameters.1.value
            # repo url
            - src:
                dependencyName: pr-run
                dataTemplate: "http://github.com/{{`{{ .Input.body.repository.owner.login }}`}}/{{`{{ .Input.body.repository.name }}`}}"
              dest: spec.arguments.parameters.2.value
            # repo ssh
            - src:
                dependencyName: pr-run
                dataTemplate: "git@github.com:{{`{{ .Input.body.repository.owner.login }}`}}/{{`{{ .Input.body.repository.name }}`}}"
              dest: spec.arguments.parameters.3.value
            # pr number
            - src:
                dependencyName: pr-run
                dataKey: body.pull_request.number
              dest: spec.arguments.parameters.4.value
            # sha
            - src:
                dependencyName: pr-run
                # dataTemplate: "{{`{{ .Input.body.pull_request.head.sha | substr 0 7 }}`}}"
                dataTemplate: "{{`{{ .Input.body.pull_request.head.sha }}`}}"
              dest: spec.arguments.parameters.5.value

      retryStrategy:
        steps: 3
