apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-access
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/hook: PreSync
  labels: {}
  refreshInterval: 1h
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-param-store
  data:
  - secretKey: token
    remoteRef:
      key: /appelsin/infra/github-access
  - secretKey: secret
    remoteRef:
      key: /appelsin/infra/webhook-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-config
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/hook: PreSync
  labels: {}
  refreshInterval: 1h
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-param-store
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: /appelsin/infra/dockerhub
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: deployment-key
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/hook: PreSync
  labels: {}
  refreshInterval: 1h
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-param-store
  data:
  - secretKey: ssh-privatekey
    remoteRef:
      key: /appelsin/infra/ssh-deploy-key
